version: "3.7"

volumes:
  app:

services:
  # API
  app:
    restart: always
    container_name: app
    working_dir: /var/www
    command: bash ./init.sh
    image: tipomrsk/rastreio.com:latest
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../nginx/config/conf.d:/etc/nginx/conf.d
      - ../nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ../app:/var/www
    depends_on:
      - app
    ports:
      - 80:80

  # MySQL
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cpfsearch
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10