version: "3.7"

volumes:
  app:

services:
  # API
  app:
    image: app
    restart: always
    container_name: app
    working_dir: /var/www
    command: bash ./init.sh
    hostname: sandbox.cpf-search
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - ../app:/var/www

  # Nginx
  nginx:
    restart: always
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ../nginx/config/conf.d:/etc/nginx/conf.d
      - ../nginx/config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - 80:80